server:
  port: 8083
spring:
  application:
    name: checkupapi # 服务名称
  cloud:
    nacos: #nacos注册中心
      server-addr: localhost:8888
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #返回json的全局时间格式
    time-zone: GMT+8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 是否开启驼峰命名规则
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #开启控制sql语句输入方便调试程序

  mapper-locations: classpath*:mapper/*Mapper.xml
swagger:
  ui-config:
    operations-sorter: method
logging:
  level:
    com.healt.cloud.checkup : debug