package com.healt.cloud.checkup.service.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2022-08-22T20:11:59.809+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://server.ws.service.checkup.cloud.healt.com", name = "HealthCheckUpWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HealthCheckUpWebServiceSoap {

    @WebMethod
    @WebResult(name = "CostChargeStateResponse", targetNamespace = "http://server.ws.service.checkup.cloud.healt.com", partName = "parameters")
    public CostChargeStateResponse costChargeState(
        @WebParam(partName = "parameters", name = "CostChargeStateRequest", targetNamespace = "http://server.ws.service.checkup.cloud.healt.com")
        CostChargeStateRequest parameters
    );
}
