package com.healt.cloud.checkup.service.ws.his;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2022-06-29T14:47:19.784+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://wegohis.com", name = "hipWebServices")
@XmlSeeAlso({ObjectFactory.class})
public interface HipWebServices {

    @WebMethod
    @RequestWrapper(localName = "message", targetNamespace = "http://wegohis.com", className = "com.healt.cloud.checkup.service.ws.his.Message")
    @ResponseWrapper(localName = "messageResponse", targetNamespace = "http://wegohis.com", className = "com.healt.cloud.checkup.service.ws.his.MessageResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public SoapResponse message(
        @WebParam(name = "Request", targetNamespace = "")
        SoapRequest request
    );
}
