
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.healt.cloud.checkup.service.ws.his;

import java.util.logging.Logger;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2022-06-29T14:47:19.774+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "HipWebServicesService",
                      portName = "hipWebServicesPort",
                      targetNamespace = "http://wegohis.com",
                      wsdlLocation = "file:/D:/ideaIU-2021.1.1.win/workspace/healt-cloud/healt-cloud-checkup-api/src/main/resources/soap.xml",
                      endpointInterface = "com.healt.cloud.checkup.service.ws.his.HipWebServices")
                      
public class HipWebServicesPortImpl implements HipWebServices {

    private static final Logger LOG = Logger.getLogger(HipWebServicesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.healt.cloud.checkup.service.ws.his.HipWebServices#message(com.healt.cloud.checkup.service.ws.his.SoapRequest  request )*
     */
    public SoapResponse message(SoapRequest request) {
        LOG.info("Executing operation message");
        System.out.println(request);
        try {
            SoapResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
