
package com.healt.cloud.checkup.service.ws.his;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2022-06-29T14:47:19.723+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class HipWebServices_HipWebServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wegohis.com", "HipWebServicesService");

    private HipWebServices_HipWebServicesPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HipWebServicesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HipWebServicesService ss = new HipWebServicesService(wsdlURL, SERVICE_NAME);
        HipWebServices port = ss.getHipWebServicesPort();  
        
        {
        System.out.println("Invoking message...");
        SoapRequest _message_request = null;
        SoapResponse _message__return = port.message(_message_request);
        System.out.println("message.result=" + _message__return);


        }

        System.exit(0);
    }

}
